version: '3'
services:
  ubuntu-dev:
    image: ubuntu:latest
    container_name: ubuntu_dev_container
    volumes:
      - ./deliveries:/home/dev/deliveries
    tty: true
    stdin_open: true
    working_dir: /home/dev/deliveries
    build:
      context: .
    command: /bin/bash
    environment:
      - TERM=xterm-256color
    networks:
      - dev-network
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - "2222:22"
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  dev-network:
    driver: bridge
